#!/usr/bin/env python
import sys
import os
import argparse

def main():
    usage = "usage: %prog [options]  "
    parser = argparse.ArgumentParser(description='Program description')
    parser.add_argument("--master", type=str, dest="master", help="file with checksums to check against\ntab delimited checksum filename")
    parser.add_argument("checksums", type=str,  help="file with checksums generated by user")

    args=parser.parse_args()

    masterdict={}

    broadict={}

    masterfh=open(args.master, 'r')
    broadfh=open(args.checksums, 'r')

    for line in masterfh:
        (checksum, filename)=line.strip().split()
        masterdict[filename]=checksum


    for line in broadfh:
        (checksum, fullpath)=line.strip().split()
        basename= os.path.basename(fullpath)
    #print checksum, basename
        broadict[basename]=checksum

    for key in masterdict.keys():
        if key not in broadict.keys():
            sys.stderr.write(key + " not in copper md5 results!\n")
            continue
        if masterdict[key] != broadict[key]:
            sys.stderr.write("md5 check sums don't match for sample: " + key + "\n")
        else:
            print "checksums match:", "\t".join([ key, masterdict[key], broadict[key] ])

if __name__ == "__main__":
    main()
